### ISSUE TITLE
Silverstripe Member forgot password emails - Help

### ISSUE THREAD

**Issue by prettytamben** [lekoala/silverstripe-email-templates#12]
Hey Thomas,

Could you elaborate on the section below from the readme please? I can't seem to find out how to adjust the config to use this module for forgot password emails:

> This nice trick is required in order for you to have consistent "Change password" and "Forgot password" emails since these are provided by the framework with no easy way to override them. It also means you can let the user add his own copy without editing translation files.

**Comment by lekoala** [comment]
Sure ! here you go. Let me know if you need anything else -:)

This nice trick is required in order for you to have consistent "Change password" and "Forgot password" emails since these are provided by the framework with no easy way to override them. It also means you can let the user add his own copy without editing translation files. In order for this to work, you need to import email templates from the framework. Please see the EmailImportTask to see how this works in more details. You can also add yourself the two following email templates with the codes ChangePassword and ForgotPassword. This works because we override the setHTMLTemplate method in order to look for a given email template matching this code.

So in LostPasswordHandler, we have:

$email = Email::create()
    ->setHTMLTemplate('SilverStripe\\Control\\Email\\ForgotPasswordEmail')
And the system will look for an email template "ForgotPassword".

**Comment by prettytamben** [comment]
Woooow, awesome :) 
Thank you!

**Comment by lekoala** [comment]
my pleasure. let me know if you see anything else, even if I use this module in prod, there are probably some rough edges here and there
